### ISSUE TITLE
Allow reading *.csv via header names instead of column numbers

### ISSUE THREAD

**Issue by PMehrfeld** [tbeu/ModelicaTableAdditions#1]
@tbeu: Is it possible to implement a function that reads in the *.csv header line, which contains the variable names, and to read in the values of these columns in the order of stated strings?

Approximately like in this screenshot:
![image](https://user-images.githubusercontent.com/11769433/116506695-0cfb9900-a8be-11eb-880f-a25dee73257c.png)

One further nice feature would of cause be, if the unit (e. g. in squared brackets in the column name) would be automatically set for the simulation. But I assume Modelica Specifications does not allow this kind of manipulation during translation?

**Comment by tbeu** [comment]
There have been similar feature requests by https://github.com/modelica/ModelicaStandardLibrary/issues/2763 and https://github.com/modelica/ModelicaStandardLibrary/issues/3252. As for units, I cannot imagine how to set a signal unit at simulation run-time. I am afraid, this is not possible in standard Modelica. But, generally, it should be possible to acquire the CSV columns by their table names. Unfortunately, it effects all code layers of the library (Modelica API, C API and C implementation). I would appreciate if you supported the development through (temporary) sponsorship by https://github.com/sponsors/tbeu. Thanks.

**Comment by PMehrfeld** [comment]
Thanks for your reply, @tbeu. Since it is not in my personal but institutional interest, unfortunately (!!) a continuous sponsoring ist not feasible. 

However, we continue using a work around similar to your code hint [here](https://github.com/modelica/ModelicaStandardLibrary/issues/2763#issuecomment-434833905).
